### PR TITLE
MkDocs prototype

### PR DESCRIPTION
**Pull request by DAKiersz**
A simple MkDocs website prototype. It works well locally, albeit with some issues related to poor docstrings which will need fixing.

You can test it locally by running `git pull`, checking out the specific branch `git checkout feature/mkdocs`, installing packages below via PIP and running `mkdocs build` from the root directory.

Requires installation of:
* mkdocs (Static site generator)
* mkdocs-material (Theme)
* "mkdocstrings[python]" (Take docstrings and build a reference)

### CODE REVIEW

**Comment by tseccull** [comment]
Hi Dominik, this is great to see! I tried running the setup by following you instructions, but all I currently get is a docs directory with a few empty .md files inside. Is that the intended outcome right now? I understand this is a work in progress, but I'm interested in whether this is what you expect it to do at this stage.

**Comment by DAKiersz** [comment]
> Hi Dominik, this is great to see! I tried running the setup by following you instructions, but all I currently get is a docs directory with a few empty .md files inside. Is that the intended outcome right now? I understand this is a work in progress, but I'm interested in whether this is what you expect it to do at this stage.

Hey Tom! Not quite sure what is happening, I will have a look at this tomorrow and see if there is a way to replicate that.
At this stage it should build a static website that extracts the docstrings from functions and formatting it on the website.

**Comment by DAKiersz** [comment]
EDIT: Here are specific instructions to run this locally, please let me know if you are still having some issues!

From the root directory of this repo:

`git checkout feature/mkdocs`
`git pull --prune`
`conda create -n mkdocs python=3.9`
`conda activate mkdocs`
`pip install mkdocs mkdocs-material "mkdocstrings[python]" pymdown-extensions`
`conda list` to verify
`mkdocs build` to build the site locally
`mkdocs server` to spin up a local server

**Comment by DAKiersz** [comment]
I need to explore this further, and this is not ready for a PR.

**Comment by tseccull** [comment]
@DAKiersz , might I suggest we use [readthedocs](https://about.readthedocs.com/?ref=readthedocs.com) instead? We'll be able to keep all the documentation files in this repo and connect it directly to the readthedocs website. We'll be able to have concurrent version control for both MOTES and its documentation. What do you think?

**Comment by DAKiersz** [comment]
> @DAKiersz , might I suggest we use [readthedocs](https://about.readthedocs.com/?ref=readthedocs.com) instead? We'll be able to keep all the documentation files in this repo and connect it directly to the readthedocs website. We'll be able to have concurrent version control for both MOTES and its documentation. What do you think?

The idea behind using MkDocs was similar, that you have a compliable documentation in-source alongside Python functions that can be referenced directly. Youcan also host it on GH pages for free.

My one immediate concern would be that the 'free' version runs ads.
https://about.readthedocs.com/pricing/#/community

Having said that, I heard that Sphinx is more flexible that MkDocs so you can definitely experiment with that if you would like to.

**Pull request closed without merging**
